### ISSUE TITLE
[bug] Argument 3 passed to ContainerView must be of the type string, null given, 

### ISSUE THREAD

**Issue by timiTao** [structurizr-php/structurizr-php#29] opened 2019-12-16 15:50 UTC
Hi,

[Started to play](https://github.com/timiTao/structurizr-poc) with this lib.

For code:
```
<?php

declare(strict_types=1);

require __DIR__ . '/general/workspace.php';

use StructurizrPHP\Core\Model\Location;

$user = $model->addPerson('User', '', Location::external());
$system = $model->addSoftwareSystem('Another system', '', Location::external());

$application = $model->addSoftwareSystem('Application', 'General application', Location::internal());
$integration = $model->addSoftwareSystem('Integration', 'General integration with 3th party', Location::external());
$user->uses($application, 'uses');
$system->usesSoftwareSystem($application, 'uses');
$application->usesSoftwareSystem($integration);

$coreContainer = $application->addContainer('Core', '', 'PHP');
$profileComponent = $coreContainer->addComponent('Profile', 'AA', '');

$coreView = $workspace->getViews()->createContainerView($application, 'Application', 'Application');
$coreView->addAllElements();
$coreView->setAutomaticLayout(true);

$applicationSystemView = $workspace->getViews()->createSystemContextView($application, 'General use', 'General architecture');
$applicationSystemView->addAllElements();
$applicationSystemView->setAutomaticLayout(true);

include_once 'general/adr.php';
include_once 'general/export.php';
```

I have output:
```
[docker://php:7.4.0-cli-alpine3.10/]:php /opt/project/diagrams/general_view.php

Fatal error: Uncaught TypeError: Argument 3 passed to StructurizrPHP\Core\View\ContainerView::__construct() must be of the type string, null given, called in /opt/project/vendor/structurizr-php/structurizr-php/src/StructurizrPHP/Core/View/ContainerView.php on line 48 and defined in /opt/project/vendor/structurizr-php/structurizr-php/src/StructurizrPHP/Core/View/ContainerView.php:21
Stack trace:
#0 /opt/project/vendor/structurizr-php/structurizr-php/src/StructurizrPHP/Core/View/ContainerView.php(48): StructurizrPHP\Core\View\ContainerView->__construct(Object(StructurizrPHP\Core\Model\SoftwareSystem), 'Core components', NULL, Object(StructurizrPHP\Core\View\ViewSet))
#1 /opt/project/vendor/structurizr-php/structurizr-php/src/StructurizrPHP/Core/View/ViewSet.php(314): StructurizrPHP\Core\View\ContainerView::hydrate(Array, Object(StructurizrPHP\Core\View\ViewSet))
#2 [internal function]: StructurizrPHP\Core\View\ViewSet::StructurizrPHP\Core\View\{closure}(Array)
#3 /opt/project/vendor/structurizr-php/structurizr-php/src/Struc in /opt/project/vendor/structurizr-php/structurizr-php/src/StructurizrPHP/Core/View/ContainerView.php on line 21

Process finished with exit code 255
```

Any ideas, what when wrong?

**Comment by norberttech** [comment] 2019-12-16 20:07
Hey, thanks for preparing that repository, it's really helpful! 
It looks that everything works fine at php 7.3, let me check at 7.4 and get back to you

**Comment by timiTao** [comment] 2019-12-16 21:14
I only see that this `key` missing value is not sent from structurizr site for `containerViews` , but when I export directly to JSON, I see it.
Exported JSON
```
        "containerViews": [
            {
                "softwareSystemId": "3",
                "description": "Core components",
                "automaticLayout": {
                    "rankDirection": "TopBottom",
                    "rankSeparation": 300,
                    "nodeSeparation": 600,
                    "edgeSeparation": 200,
                    "vertices": false
                },
                "elements": [
                    {
                        "id": "1",
                        "x": 0,
                        "y": 0
                    },
                    {
                        "id": "2",
                        "x": 0,
                        "y": 0
                    },
                    {
                        "id": "3",
                        "x": 0,
                        "y": 0
                    },
                    {
                        "id": "4",
                        "x": 0,
                        "y": 0
                    },
                    {
                        "id": "8",
                        "x": 0,
                        "y": 0
                    }
                ],
                "relationships": [
                    {
                        "id": "5"
                    },
                    {
                        "id": "6"
                    },
                    {
                        "id": "7"
                    }
                ],
                "key": "_1",
                "animations": []
            }
        ],
```

local `var_dump`:
```
{
  "containerViews": [
    {
      "softwareSystemId": "3",
      "description": "Core components",
      "automaticLayout": {
        "rankDirection": "TopBottom",
        "rankSeparation": 300,
        "nodeSeparation": 600,
        "edgeSeparation": 200,
        "vertices": false
      },
      "elements": [
        {
          "id": "1",
          "x": 0,
          "y": 0
        },
        {
          "id": "2",
          "x": 0,
          "y": 0
        },
        {
          "id": "3",
          "x": 0,
          "y": 0
        },
        {
          "id": "4",
          "x": 0,
          "y": 0
        },
        {
          "id": "8",
          "x": 0,
          "y": 0
        }
      ],
      "relationships": [
        {
          "id": "5"
        },
        {
          "id": "6"
        },
        {
          "id": "7"
        }
      ]
    }
}
```

When I edited the diagram at web editor, `key` started to appear and bug disappears.
I assume, the view was wrongly sent via the client.

**Comment by norberttech** [comment] 2019-12-22 20:52
Hey, I double checked everything and I can't reproduce this issue locally. I tried almost everything, including creating everything from the scratch, using your code and then changing through UI - I can't reproduce this one. 
I'm closing it for now, if you or anyone else find a way to reproduce this issue locally and describe it I promise to fix it.

**Closed as completed by norberttech** 2019-12-22 20:52 UTC
