### ISSUE TITLE
Getting Started Example not working

### ISSUE THREAD

**Issue by dmlb2000** [structurizr-php/structurizr-php#42] opened 2020-08-11 03:21 UTC
Not sure why the example isn't working... here's my code.

```
<?php

use Monolog\Handler\StreamHandler;
use Monolog\Logger;
use StructurizrPHP\Client\Client;
use StructurizrPHP\Client\Credentials;
use StructurizrPHP\Client\Infrastructure\Http\SymfonyRequestFactory;
use StructurizrPHP\Client\UrlMap;
use StructurizrPHP\Core\Model\Relationship\InteractionStyle;
use StructurizrPHP\Core\Model\Enterprise;
use StructurizrPHP\Core\Model\Location;
use StructurizrPHP\Core\Model\Tags;
use StructurizrPHP\Core\View\Configuration\Shape;
use StructurizrPHP\Core\Workspace;
use Symfony\Component\HttpClient\Psr18Client;

require __DIR__ . '/vendor/autoload.php';

# workspace ID
$workspace_id = XXXXX;

# api key
$api_key = XXXXXX;

# api secret
$api_secret = XXXXXX;

$workspace = new Workspace(
    $id = $workspace_id,
    $name = 'Getting Started',
    $description = 'This is a model of my software system. by structurizr-php/structurizr-php'
);
$workspace->getModel()->setEnterprise(new Enterprise('Structurizr PHP'));
$person = $workspace->getModel()->addPerson(
    $name = 'User',
    $description = 'A user of my software system.',
    Location::internal()
);
$softwareSystem = $workspace->getModel()->addSoftwareSystem(
    $name = 'Software System',
    $description = 'My software system.',
    Location::internal()
);
$person->usesSoftwareSystem($softwareSystem);

$contextView = $workspace->getViews()->createSystemContextView($softwareSystem, 'System Context', 'An example of a System Context diagram.');
$contextView->addAllElements();
$contextView->setAutomaticLayout(true);

$styles = $workspace->getViews()->getConfiguration()->getStyles();

$styles->addElementStyle(Tags::SOFTWARE_SYSTEM)->background("#1168bd")->color('#ffffff');
$styles->addElementStyle(Tags::PERSON)->background("#08427b")->color('#ffffff')->shape(Shape::person());

$client = new Client(
    new Credentials($api_key, $api_secret),
    new UrlMap('https://api.structurizr.com'),
    new Psr18Client(),
    new SymfonyRequestFactory(),
    new Logger('structurizr', [new StreamHandler('php://stdout')])
);
$client->put($workspace);
```

The output seems to be something about the relationship not being hydrated!!! I thought water and computing equipment don't mix!

```
[2020-08-11T03:17:24.172701+00:00] structurizr.DEBUG: Post GET workspace {"workspace":{"id":57388,"name":"Pacifica Top Level","description":"A Pacifica highest level architecture diagram.","revision":3,"lastModifiedDate":"2020-08-10T19:36:54Z","model":{"people":[{"id":"2","tags":"Element,Person","name":"User","description":"The user interested in data.","relationships":[{"id":"3","tags":"Relationship,Synchronous","sourceId":"2","destinationId":"1"}],"location":"Unspecified"}],"softwareSystems":[{"id":"1","tags":"Element,Software System","name":"Data Management System","description":"The core of the data management system.","location":"Unspecified"}]},"documentation":[],"views":{"systemContextViews":[{"softwareSystemId":"1","description":"Description","key":"SystemContext","enterpriseBoundaryVisible":true}],"configuration":{"branding":[],"styles":[],"terminology":[]}}}} []
PHP Notice:  Undefined index: interactionStyle in /c/Users/dmlb2000/Projects/Pacifica/architecture-diagram-structurizr/vendor/structurizr-php/structurizr-php/src/StructurizrPHP/Core/Model/Relationship.php on line 152
PHP Fatal error:  Uncaught TypeError: Argument 1 passed to StructurizrPHP\Core\Model\Relationship\InteractionStyle::hydrate() must be of the type string, null given, called in /c/Users/dmlb2000/Projects/Pacifica/architecture-diagram-structurizr/vendor/structurizr-php/structurizr-php/src/StructurizrPHP/Core/Model/Relationship.php on line 152 and defined in /c/Users/dmlb2000/Projects/Pacifica/architecture-diagram-structurizr/vendor/structurizr-php/structurizr-php/src/StructurizrPHP/Core/Model/Relationship/InteractionStyle.php:42
Stack trace:
#0 /c/Users/dmlb2000/Projects/Pacifica/architecture-diagram-structurizr/vendor/structurizr-php/structurizr-php/src/StructurizrPHP/Core/Model/Relationship.php(152): StructurizrPHP\Core\Model\Relationship\InteractionStyle::hydrate(NULL)
#1 /c/Users/dmlb2000/Projects/Pacifica/architecture-diagram-structurizr/vendor/structurizr-php/structurizr-php/src/StructurizrPHP/Core/Model/Element.php(192): StructurizrPHP\Core\Model\Relationship::hydrate(Array, Object(StructurizrPHP\Core\Model\Person), Objec in /c/Users/dmlb2000/Projects/Pacifica/architecture-diagram-structurizr/vendor/structurizr-php/structurizr-php/src/StructurizrPHP/Core/Model/Relationship/InteractionStyle.php on line 42
```

**Comment by norberttech** [comment] 2020-08-18 09:11
Hey David, sorry to hear that getting started example does not work for you. 
I was trying to reproduce this issue locally and it works perfectly fine but before we move anywhere further could you please let me know if you maybe changed the workspace manually through https://structurizr.com/ web user interface?
If you did it's possible that you generated and edge case for the client which is not capable to perform merge before put. 

You might want to try this:

```diff
+ $client->setMergeRemote(false);
$client->put($workspace);
```

It will prevent the client from fetching workspace and merging it with your local model before it put it online. 
**But be careful, this will override any manual changes made over the UI.** 

> I thought water and computing equipment don't mix!

as for the hydration, the name might be a bit confusing because it should refer to the process described here https://stackoverflow.com/a/6991192 so in our case it's more deserialization rather than hydration however our static factories first create the object and then populates it using direct access to private properties which +/- fits the definition of the object hydration.

**Comment by norberttech** [comment] 2020-08-24 07:53
I'm closing this one, if the solution I gave you won't work feel free to create a new issue, thanks!

**Closed as completed by norberttech** 2020-08-24 07:53 UTC
